#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lefty,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           righty,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           lf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rf,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rb,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true) {

		motor[lf] = vexRT[Ch3] + vexRT[Ch4] + vexRT[Ch1];
		motor[rf] = -(vexRT[Ch3] - vexRT[Ch4] - vexRT[Ch1]);
		motor[lb] = vexRT[Ch3] + vexRT[Ch4] - vexRT[Ch1];
		motor[rb] = -(vexRT[Ch3] - vexRT[Ch4] + vexRT[Ch1]);

		if(vexRT[Btn5U] == 1 || vexRT[Btn6U] == 1) {
				motor[left] = 70;
				motor[lefty] = 70;
				motor[right] = 70;
				motor[righty] = 70;
	}
		else if(vexRT[Btn5D] == 1 || vexRT[Btn6D] == 1) {
				motor[left] = -70;
				motor[lefty] = -70;
				motor[righty] = -70;
				motor[right] = -70;
	}
		else {
				motor[left] = 0;
				motor[lefty] = 0;
				motor[righty] = 0;
				motor[right] = 0;
	}
}

}
